name = "course-spider"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "course_spider_db"
database_name = "course-spider-db"
database_id = "3ac7b642-4ccb-4a0f-9bc5-2ff6594dc736" # Run 'npx wrangler d1 create course-spider-db' to get this ID
